export const QUESTIONS = [
  'Una cosa che non diresti mai al tuo capo',
  'Il peggior regalo di compleanno possibile',
  'Una cosa che non vorresti mai trovare nel tuo letto',
  'Il nome perfetto per un gatto snob',
  'Cosa pensano davvero i cani di noi',
  'Una scusa geniale per arrivare in ritardo',
  'La cosa più strana da dire al primo appuntamento',
  'Cosa c’è davvero nel Triangolo delle Bermuda',
  'Il titolo della tua autobiografia',
  'Una cosa che faresti se fossi invisibile per un giorno',
  'Il peggior nome per una pizzeria',
  'Una legge che faresti approvare se fossi presidente per un giorno',
  'Una cosa da non fare mai in ascensore',
  'Il superpotere più inutile di sempre',
  'Cosa urleresti lanciandoti col paracadute',
  'Una frase che i nonni dicono sempre',
  'Il peggior slogan per un’agenzia di pompe funebri',
  'Un gusto di gelato che nessuno ha mai osato inventare',
  'Cosa direbbe il tuo frigorifero se potesse parlare',
  'Il vero motivo per cui i dinosauri si sono estinti',
  'Una cosa che non dovresti mai scrivere nel gruppo di famiglia',
  'La scusa peggiore per non andare a una festa',
  'Il nome di una band che non avrà mai successo',
  'Cosa si nasconde nella borsa di Mary Poppins',
  'Una cosa che faresti con un milione di euro da spendere in un’ora',
  'Il peggior consiglio da dare a un bambino',
  'Cosa pensa davvero un piccione in piazza',
  'Una cosa che non vorresti sentire dal tuo dentista',
  'Una cosa che non vorresti sentire dal pilota dell’aereo',
  'Il peggior tema per un matrimonio',
  'Una cosa da mettere in una capsula del tempo',
  'L’hashtag della tua vita',
  'Il lavoro peggiore del mondo',
  'Cosa farebbero gli alieni appena atterrati in Italia',
  'Il primo pensiero appena svegli il lunedì',
  'Una regola segreta per sopravvivere al pranzo di Natale',
  'Il piatto più disgustoso che si possa ordinare',
  'Il miglior insulto senza parolacce',
  'Cosa dice di te la tua playlist',
  'Il nome di un profumo che nessuno comprerebbe',
  'Dove vanno davvero i calzini spaiati',
  'Il peggior motto per una scuola',
  'Una cosa che non porteresti mai su un’isola deserta',
  'La frase più banale da scrivere su un biglietto d’auguri',
  'Il momento peggiore per starnutire',
  'Il nome di un pianeta appena scoperto',
  'Una cosa che si dice al proprio riflesso nello specchio',
  'Il segreto per vivere fino a 120 anni',
  'Il prossimo grande trend sui social',
  'Cosa direbbe un gatto al suo veterinario',
  'Una cosa che non dovresti mai cercare su Google',
  'Il peggior regalo per San Valentino',
  'Un film che non avrebbe mai dovuto avere un sequel',
  'Cosa c’è scritto nel manuale segreto delle mamme',
  'Una cosa che fai quando nessuno ti guarda',
  'Il posto peggiore per un primo bacio',
  'Il nome perfetto per un pesce rosso',
  'Un’invenzione inutile ma geniale',
  'Cosa direbbe di te il tuo cuscino',
  'La domanda che faresti a un indovino',
  'Una cosa da non dire mai a un colloquio di lavoro',
  'Il peggior souvenir delle vacanze',
  'Il peggior nome per una barca',
  'Un consiglio che daresti a te stesso di dieci anni fa',
  'Una tradizione di famiglia completamente inventata',
  'Il motivo segreto per cui le lumache sono così lente',
  'Una cosa da non fare mai in un museo',
  'Il peggior gusto di patatine',
  'Cosa farebbe Babbo Natale in pensione',
  'Il nome della tua futura startup',
  'Il messaggio vocale peggiore da ricevere alle 3 di notte',
  'Una cosa che la gente fa in palestra ma non dovrebbe',
  'Il peggior nome per un supereroe',
  'Il messaggio da lasciare agli alieni',
  'Il posto peggiore dove rimanere bloccati',
  'Cosa grideresti vincendo alla lotteria',
  'Il soprannome che non vorresti mai avere',
  'Una cosa che non ti aspetteresti mai di trovare in una pizza',
  'Cosa sognano le piante',
  'Il vero motivo per cui il vicino fa rumore di notte',
  'Una scusa per non lavare i piatti',
  'Il peggior consiglio d’amore',
  'Una nuova materia da insegnare a scuola',
  'Il peggior nome per un’app di incontri',
  'Cosa diresti incontrando te stesso dal futuro',
  'Il titolo di un reality che nessuno guarderebbe',
  'Una cosa da non dire mai alla suocera',
  'L’ultima cosa che vorresti sentire prima di un esame',
  'Il vero motivo per cui la Torre di Pisa pende',
  'Una cosa che faresti se fossi un fantasma',
  'Il nome di un cocktail terribile',
  'Cosa c’è sotto il letto di un mostro',
  'Una frase per scappare da una conversazione noiosa',
  'Il peggior nome per un ristorante di sushi',
  'Un talento nascosto che nessuno sospetta',
  'Una cosa che si trova solo nei cassetti delle nonne',
  'L’oggetto più inutile da portare in campeggio',
  'Il primo comandamento del perfetto pigro',
  'Cosa farebbero i tuoi animali se diventassero i padroni di casa',
  'Un programma TV che non ammetteresti mai di guardare',
  'La password più prevedibile del mondo',
  'Il peggior modo per chiedere qualcuno in sposo',
  'Cosa succede davvero quando spegni la luce del frigo',
  'Il peggior nome per un’auto',
  'Una cosa che diresti per impressionare un italiano all’estero',
];
